// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineDebitApp.Data;

namespace OnlineDebitApp.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("OnlineDebitApp.Models.ItemData", b =>
                {
                    b.Property<int>("paymentDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("cardNumber")
                        .HasColumnType("text");

                    b.Property<string>("cardOwnerName")
                        .HasColumnType("text");

                    b.Property<string>("expirationDate")
                        .HasColumnType("text");

                    b.Property<string>("securityCode")
                        .HasColumnType("text");

                    b.HasKey("paymentDetailId");

                    b.ToTable("CreditCardDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
